feature/fix-bug-filter-user
alexanderchernetsky/dream-team-tool pull request #37
Opened 2021-06-18 15:11 UTC by AlexeyGrishechkin

fix search handler and filter users

2021-06-19 12:37 UTC, alexanderchernetsky requested changes

2021-06-19 12:37 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
>        }
Is it a new feature??? Or it's a bug fix? Please rename the branch

2021-06-19 12:37 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
> +        `${createSearchString({  [`${selectName}`]: value })}`
You're resetting another filter. This is incorrect behaviour! https://streamable.com/sok5jo

2021-06-21 11:54 UTC, AlexeyGrishechkin commented on src/pages/HomepageManager/index.tsx
>        }
fixed

2021-06-21 11:57 UTC, AlexeyGrishechkin commented on src/pages/HomepageManager/index.tsx
> +        `${createSearchString({  [`${selectName}`]: value })}`
fixed

2021-06-28 11:02 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
>        }
not fixed. the name of the branch is still incorrect. It should be sth like: bugfix/user-filter

2021-07-03 07:17 UTC, closed without merging