Features/employee details page
alexanderchernetsky/dream-team-tool pull request #38
Opened 2021-06-18 15:16 UTC by AlexeyGrishechkin

2021-06-19 12:26 UTC, alexanderchernetsky requested changes
I see your idea of re-using an existing page. But in this case I wanted you to create a new one. That's for the sake of exercise.  So please create new page, try to think up new design etc.

2021-06-19 12:26 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
> +        `${createSearchString({  [`${selectName}`]: value })}`
Is this change related to the new page? If NOT - it shouldn't be a part of this PR!

2021-06-19 12:26 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
> +        `${createSearchString({  [`${selectName}`]: value })}`
It applies to other changes below

2021-06-19 12:26 UTC, alexanderchernetsky commented on package-lock.json
> +{
this file should be excluded from the PR

2021-06-19 12:26 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
> +            href={`/employee-details/${data.id}`}
The functionality is NOT working at all. You MUST check how the app works before creating the PR! https://streamable.com/ga3zxx

2021-06-23 07:06 UTC, AlexeyGrishechkin commented on src/pages/HomepageManager/index.tsx
> +        `${createSearchString({  [`${selectName}`]: value })}`
rollbacked this

2021-06-23 07:07 UTC, AlexeyGrishechkin commented on package-lock.json
> +{
exclude this file

2021-06-23 07:07 UTC, AlexeyGrishechkin commented on src/pages/HomepageManager/index.tsx
> +            href={`/employee-details/${data.id}`}
fixed

2021-06-28 11:46 UTC, alexanderchernetsky requested changes

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +  background: url("https://st4.cannypic.com/thumbs/42/422973_632_canny_pic.jpg")
You should upload the image locally

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +  imageSrc?: string;
Why have you marked all the fields as optional?

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +  fullName = "Full Name",
Most of these default values just don't have sense, thus, should be removed

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +    <Wrapper>
After looking into the markup, I've noticed that almost all tags are 'div'. Do you know any other tags? Have you heard about 'semantic markup'? Please learn about it and rewrite the markup in more semantic way.

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +                  key={index}
the key is applied to the wrong element. You will notice the warning in the console

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +              <div style={{ margin: "0 auto" }}>
Don't ever use inline styles! Please use styled components for styling

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/pages/HomepageManager/index.tsx
> +      delete urlParams.page;
this bugfix should not be a part of this PR. Please remove

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/pages/EmployeeDetails/index.tsx
> +  const id = location.pathname.replace("/employee-details/", "");
This replace is unnecessary. You can get id from params. Please rewrite

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/pages/EmployeeDetails/index.tsx
> +      {!loginStore?.user ? (
please simplify the logic. Remove ! operator and then rewrite ternary op.

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/pages/EmployeeDetails/index.tsx
> +          <Header pageTitle="Employee Details" />
I think this header can be shown anyways

2021-06-28 11:46 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +            {capitalize(focus)} <JobName>— {jobTitle}</JobName>
Could you please remove the hyphen? It should look better without it.

2021-06-28 11:50 UTC, alexanderchernetsky commented
You have a flickering issue on the page. https://streamable.com/u9ongs You can use network throttling to see it clearly. Please fix the issue.

2021-06-30 14:00 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +  background: url("https://st4.cannypic.com/thumbs/42/422973_632_canny_pic.jpg")
done

2021-06-30 14:00 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +  imageSrc?: string;
fixed

2021-06-30 14:00 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +  fullName = "Full Name",
fixed

2021-06-30 14:00 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +    <Wrapper>
fixed

2021-06-30 14:00 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +                  key={index}
fixed

2021-06-30 14:03 UTC, AlexeyGrishechkin commented on src/pages/HomepageManager/index.tsx
> +      delete urlParams.page;
removed

2021-06-30 14:03 UTC, AlexeyGrishechkin commented on src/pages/EmployeeDetails/index.tsx
> +  const id = location.pathname.replace("/employee-details/", "");
fixed

2021-06-30 14:03 UTC, AlexeyGrishechkin commented on src/pages/EmployeeDetails/index.tsx
> +      {!loginStore?.user ? (
fixed

2021-06-30 14:03 UTC, AlexeyGrishechkin commented on src/pages/EmployeeDetails/index.tsx
> +          <Header pageTitle="Employee Details" />
fixed

2021-06-30 14:04 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +            {capitalize(focus)} <JobName>— {jobTitle}</JobName>
fixed

2021-07-03 07:36 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +  background: url("https://st4.cannypic.com/thumbs/42/422973_632_canny_pic.jpg")
the image doesn't exist locally. And it's the reason why the app crashes.

2021-07-03 08:16 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +const Wrapper = styled.main`
Remove empty space from the top of the page https://ibb.co/Y0ZL0VY

2021-07-03 08:16 UTC, alexanderchernetsky commented on src/components/EmployeeInfo.tsx
> +const LinksWrapper = styled.section`
you're rendering a list. Isn't it semantically better to use ul and li tags?

2021-07-03 08:16 UTC, alexanderchernetsky commented on src/pages/EmployeeDetails/index.tsx
> +      {!loginStore?.user ? (
You made a mistake after re-writing. Now you have 100px of redundant space at the top of your page. It belongs to SpinnerWrapper. You shouldn't have removed ternary operator. I asked you to re-write it.

2021-07-03 08:18 UTC, alexanderchernetsky requested changes
You still have flickering on your page (image placeholder is shown initially) Please fix it.

2021-07-13 08:05 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +  background: url("https://st4.cannypic.com/thumbs/42/422973_632_canny_pic.jpg")
fixed

2021-07-13 08:05 UTC, AlexeyGrishechkin commented on src/pages/EmployeeDetails/index.tsx
> +      {!loginStore?.user ? (
fixed

2021-07-13 08:06 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +const JobInfo = styled.h3`
fixed

2021-07-13 08:07 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +const Wrapper = styled.main`
done

2021-07-13 08:07 UTC, AlexeyGrishechkin commented on src/components/EmployeeInfo.tsx
> +const LinksWrapper = styled.section`
fixed

2021-07-17 11:26 UTC, alexanderchernetsky approved these changes

2021-07-17 11:26 UTC, merged